export enum PlanType {
  BASIC = 'BASIC',
  PRO = 'PRO',
  ENTERPRISE = 'ENTERPRISE',
  TRIAL = 'TRIAL',
}

export enum CompanyStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  CANCELLED = 'CANCELLED',
  TRIAL = 'TRIAL',
}

export enum SchedulingMode {
  SCHEDULE_ONLY = 'SCHEDULE_ONLY',
  QUEUE_ONLY = 'QUEUE_ONLY',
  HYBRID = 'HYBRID',
}

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  RECEPTIONIST = 'RECEPTIONIST',
}

export enum AppointmentStatus {
  SCHEDULED = 'SCHEDULED',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
}

export enum QueueStatus {
  WAITING = 'WAITING',
  CALLED = 'CALLED',
  IN_SERVICE = 'IN_SERVICE',
  DONE = 'DONE',
  LEFT = 'LEFT',
}

export enum QueuePriority {
  NORMAL = 'NORMAL',
  VIP = 'VIP',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  REFUNDED = 'REFUNDED',
  FAILED = 'FAILED',
}

export enum PaymentMethod {
  PIX = 'PIX',
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  CASH = 'CASH',
  COURTESY = 'COURTESY',
}

export enum DayOfWeek {
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
  SUNDAY = 'SUNDAY',
}

export enum NotificationType {
  APPOINTMENT_CONFIRMED = 'APPOINTMENT_CONFIRMED',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_NO_SHOW = 'APPOINTMENT_NO_SHOW',
  QUEUE_CALLED = 'QUEUE_CALLED',
  QUEUE_POSITION = 'QUEUE_POSITION',
  PAYMENT_LINK = 'PAYMENT_LINK',
  RETURN_REMINDER = 'RETURN_REMINDER',
  CUSTOM = 'CUSTOM',
}

export enum BotStep {
  IDLE = 'IDLE',
  MAIN_MENU = 'MAIN_MENU',
  BOOKING_SELECT_SERVICE = 'BOOKING_SELECT_SERVICE',
  BOOKING_SELECT_COLLABORATOR = 'BOOKING_SELECT_COLLABORATOR',
  BOOKING_SELECT_DATE = 'BOOKING_SELECT_DATE',
  BOOKING_SELECT_TIME = 'BOOKING_SELECT_TIME',
  BOOKING_UPLOAD_DOCUMENT = 'BOOKING_UPLOAD_DOCUMENT',
  BOOKING_PAYMENT = 'BOOKING_PAYMENT',
  BOOKING_CONFIRM = 'BOOKING_CONFIRM',
  CANCEL_LIST = 'CANCEL_LIST',
  CANCEL_CONFIRM = 'CANCEL_CONFIRM',
  RESCHEDULE_SELECT = 'RESCHEDULE_SELECT',
  RESCHEDULE_DATE = 'RESCHEDULE_DATE',
  RESCHEDULE_TIME = 'RESCHEDULE_TIME',
  RESCHEDULE_CONFIRM = 'RESCHEDULE_CONFIRM',
  QUEUE_JOIN = 'QUEUE_JOIN',
  QUEUE_SELECT_SERVICE = 'QUEUE_SELECT_SERVICE',
  QUEUE_CONFIRM = 'QUEUE_CONFIRM',
  QUEUE_POSITION = 'QUEUE_POSITION',
  PRESENCE_CONFIRM = 'PRESENCE_CONFIRM',
}

export enum AuditAction {
  APPOINTMENT_CREATED = 'APPOINTMENT_CREATED',
  APPOINTMENT_UPDATED = 'APPOINTMENT_UPDATED',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_COMPLETED = 'APPOINTMENT_COMPLETED',
  APPOINTMENT_NO_SHOW = 'APPOINTMENT_NO_SHOW',
  CLIENT_CREATED = 'CLIENT_CREATED',
  CLIENT_BLOCKED = 'CLIENT_BLOCKED',
  CLIENT_AUTO_BLOCKED = 'CLIENT_AUTO_BLOCKED',
  CLIENT_UNBLOCKED = 'CLIENT_UNBLOCKED',
  QUEUE_JOINED = 'QUEUE_JOINED',
  QUEUE_CALLED = 'QUEUE_CALLED',
  QUEUE_COMPLETED = 'QUEUE_COMPLETED',
  PAYMENT_CREATED = 'PAYMENT_CREATED',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  USER_LOGIN = 'USER_LOGIN',
  USER_CREATED = 'USER_CREATED',
  SETTINGS_UPDATED = 'SETTINGS_UPDATED',
}
